name: Build Application - Push to Registry
on:
  workflow_call:
    inputs:
      image_repository:
        description: The image repository for the built images, defaults to value of `Image.repository` from `values.yaml`
        required: false
        default: nexus.sam-app.ro:5000
        type: string
      image_tag:
        description: Built image tag, defaults to value of `Image.tag` from `values.yaml`
        required: false
        default: ''
        type: string
      target:
        description: The build target if the image needs to be build to a certain layer e.g. builder
        required: false
        default: 'builder'
        type: string
      test_commands:
        description: The commands to run in the development container for executing tests/linting, one per line
        required: false
        default: ''
        type: string
      results_path:
        description: The directory(in the container) where the results will be stored
        required: false
        default: /tmp
        type: string
      slack_channel:
        description: The Slack channel where you want your notifications being sent
        required: false
        default: ''
        type: string
      project_dir:
        description: The application/project folder relative to git root
        required: false
        default: '.'
        type: string

jobs:
  application_build:
    runs-on: [ "self-hosted", "payments-tribe" ]
    outputs:
      image_tag: ${{ steps.build-final-container.outputs.image_tag }}
      imageSha: ${{ steps.build-final-container.outputs.imageSha }}
    steps:
      - name: "☁️ Check out project code"
        # actions checkout v 3.0.2
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: "☁️ Check out payments composite actions"
        # actions checkout v 3.0.2
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          repository: 'sumup/payments-composite-actions'
          token: ${{ secrets.GH_ACTIONS_CI_TOKEN }}
          path: .github/payments-composite-actions
          ref: '0.1.5'

      - name: "📦 Build development container"
        id: build-development-container
        if: inputs.test_commands != ''
        uses: ./.github/payments-composite-actions/docker/build
        with:
          image_repository: ${{ inputs.image_repository }}
          image_tag: ${{ inputs.image_tag }}
          project_dir: ${{ inputs.project_dir }}
          target: ${{ inputs.target }}
          ssh_agent_key: ${{ secrets.ACTIONS_SSH_AGENT_KEY }}

      - name: "🧪 Run tests in development container"
        if: inputs.test_commands != ''
        uses: ./.github/payments-composite-actions/docker/run-builder-tests
        with:
          image_full_name: ${{ steps.build-development-container.outputs.image_full_name }}
          results_path: ${{ inputs.results_path }}
          test_commands: ${{ inputs.test_commands }}

      - name: "📦 Build final container"
        id: build-final-container
        uses: ./.github/payments-composite-actions/docker/build
        with:
          image_repository: ${{ inputs.image_repository }}
          image_tag: ${{ inputs.image_tag }}
          project_dir: ${{ inputs.project_dir }}
          ssh_agent_key: ${{ secrets.ACTIONS_SSH_AGENT_KEY }}

      - name: "🔍 Scan container"
        id: call-scan-container
        uses: ./.github/payments-composite-actions/docker/trivy-scan
        with:
          github_token: ${{ secrets.GH_ACTIONS_CI_TOKEN }}
          image_full_name: ${{ steps.build-final-container.outputs.image_full_name }}

      - name: "🗃️ Publish container"
        id: call-publish-container
        uses: ./.github/payments-composite-actions/docker/push
        with:
          image_full_name: ${{ steps.build-final-container.outputs.image_full_name }}
          image_repository: ${{ inputs.image_repository }}
          iam_login: true

      - name: "📝 Docker build info"
        id: docker_build_info
        run: |
          echo "#### Build docker image: ${{ steps.build-final-container.outputs.image_full_name }}" >> $GITHUB_STEP_SUMMARY

      - name: "✉️ Send Slack message on failure"
        if: failure() }} && inputs.slack_channel != ''
        uses: ./.github/payments-composite-actions/notifications/slack-send
        with:
          slack_bot_token: ${{ secrets.GH_ACTIONS_SLACK_TOKEN }}
          slack_channel: ${{ inputs.slack_channel }}
          color: "danger"
          message: "The Github Actions build has failed!"


  ####
  ####   Send Slack notification
  ####
  notification:
    runs-on: ["self-hosted", "payments-tribe"]
    needs: [ 'application_build']
    if: inputs.slack_channel != ''
    steps:
      - name: "☁️ Check out payments composite actions"
        # actions checkout v 3.0.2
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          repository: 'sumup/payments-composite-actions'
          token: ${{ secrets.GH_ACTIONS_CI_TOKEN }}
          path: .github/payments-composite-actions
          ref: '0.1.5'

      - name: "✉️ Send slack message on success"
        if: success()
        uses: ./.github/payments-composite-actions/notifications/slack-send
        with:
          slack_bot_token: ${{ secrets.GH_ACTIONS_SLACK_TOKEN }}
          slack_channel: ${{ inputs.slack_channel }}
          color: "good"
          # TODO: Maybe add full published image name
          message: "The application build & push has completed successfully!"
