name: Test Helm chart
on:
  workflow_call:
    inputs:
      slack_channel:
        description: The Slack channel where you want your notifications being sent
        required: false
        default: ''
        type: string
      project_dir:
        description: The application/project folder relative to git root
        required: false
        default: '.'
        type: string

jobs:
  ####
  ####   CHART TEST
  ####
  chart_test:
    runs-on: ["self-hosted", "payments-tribe"]
    steps:
      - name: "☁️ Check out project code"
        # actions checkout v 3.0.2
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: "☁️ Check out payments composite actions"
        # actions checkout v 3.0.2
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          repository: 'sumup/payments-composite-actions'
          token: ${{ secrets.GH_ACTIONS_CI_TOKEN }}
          path: .github/payments-composite-actions
          ref: '0.3.0'

      - name: "🧪 Test Helm chart"
        uses: ./.github/payments-composite-actions/helm/ct-test

      - name: "✉️ Send Slack message on failure"
        if: failure() && inputs.slack_channel != ''
        uses: ./.github/payments-composite-actions/notifications/slack-send
        with:
          slack_bot_token: ${{ secrets.GH_ACTIONS_SLACK_TOKEN }}
          slack_channel: ${{ inputs.slack_channel }}
          color: "danger"
          message: "The Helm chart tests have failed!"
  ####
  ####   Send Slack notification
  ####
  notification:
    runs-on: ["self-hosted", "payments-tribe"]
    needs: ['chart_test']
    if: inputs.slack_channel != ''
    steps:
      - name: "☁️ Check out payments composite actions"
        # actions checkout v 3.0.2
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          repository: 'sumup/payments-composite-actions'
          token: ${{ secrets.GH_ACTIONS_CI_TOKEN }}
          path: .github/payments-composite-actions
          ref: '0.3.0'

      - name: "✉️ Send slack message on success"
        if: success()
        uses: ./.github/payments-composite-actions/notifications/slack-send
        with:
          slack_bot_token: ${{ secrets.GH_ACTIONS_SLACK_TOKEN }}
          slack_channel: ${{ inputs.slack_channel }}
          color: "good"
          message: "The application build has completed successfully!"
