name: Build Helm Chart, Push and Deploy
on:
  workflow_call:
    inputs:
      chart_repository:
        required: true
        type: string
      deployment_config_path:
        description: The path to the configuration file that needs to be updated
        required: true
        type: string
      deployment_environment:
        description: The deployment environment
        default: 'Theta'
        required: false
        type: string
      slack_channel:
        description: The Slack channel where you want your notifications being sent
        required: false
        default: ''
        type: string
      project_dir:
        description: The application/project folder relative to git root
        required: false
        default: '.'
        type: string

jobs:
  ####
  ####   CHART TEST AND BUILD
  ####
  chart_changes:
    runs-on: ["self-hosted", "payments-tribe"]
    outputs:
      changeset: ${{ steps.get_changes.outputs.changeset }}
    steps:
      - name: "☁️ Check out project code"
        # actions checkout v 3.0.2
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 2

      - name: "📝 Get changes from last commit"
        id: get_changes
        run: |
          changeset=false
          echo "::debug:: last commit raw # $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
          for change in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}); do
            parent_dir=$(dirname "$change")
            echo "::debug::=== change at $parent_dir"
            if echo $parent_dir | grep -q '.deployment/chart'; then
               changeset=true
               echo "::debug:: located chart change in $change, triggering rebuild"
               break
            fi
          done
          echo "::set-output name=changeset::${changeset}"

  chart_build:
    runs-on: ["self-hosted", "payments-tribe"]
    outputs:
      chart_version: ${{ steps.package-chart.outputs.chart_version }}
    needs: ['chart_changes']
    if: ${{ needs.chart_changes.outputs.changeset == 'true' }}
    steps:
      - name: "☁️ Check out project code"
        # actions checkout v 3.0.2
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: "☁️ Check out payments composite actions"
        # actions checkout v 3.0.2
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          repository: 'sumup/payments-composite-actions@0.1.0'
          token: ${{ secrets.GH_ACTIONS_CI_PAT }}
          path: .github/payments-composite-actions
          ref: 'main'

      - name: "🧪 Test Helm chart"
        uses: ./.github/payments-composite-actions/helm/ct-test

      - name: "📦 Build Helm package"
        id: package-chart
        uses: ./.github/payments-composite-actions/helm/package
        with:
          project_dir: ${{ inputs.project_dir }}
          chart_repository: ${{ inputs.chart_repository }}

      - name: "📝 Chart build info"
        id: chart_build_info
        run: |
          echo "#### Build helm chart: ${{ inputs.chart_repository }}/${{ steps.package-chart.outputs.chart_name }}/${{ steps.package-chart.outputs.chart_version }}" >> $GITHUB_STEP_SUMMARY
      
      - name: "✉️ Send Slack message on failure"
        if: ${{ failure() }}
        uses: ./.github/payments-composite-actions/notifications/slack-send
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_channel: ${{ inputs.slack_channel }}
          color: "danger"
          message: "Building Helm package has failed!"

  ####
  ####   Deploy infra update
  ####
  deploy_repo:
    runs-on: ["self-hosted", "payments-tribe"]
    needs: ['chart_build']
    if: always() && needs.chart_build.result != 'failure'
    outputs:
      pr_number: ${{ steps.deploy_infra_update.outputs.pr_number }}
    steps:
      - name: "☁️ Check out project code"
        # actions checkout v 3.0.2
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 2

      - name: "☁️ Check out payments composite actions"
        # actions checkout v 3.0.2
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          repository: 'sumup/payments-composite-actions@0.1.0'
          token: ${{ secrets.GH_ACTIONS_CI_PAT }}
          path: .github/payments-composite-actions
          ref: 'main'

      - name: "🚀 Push changes to deploy infra repo"
        id: deploy_infra_update
        uses: ./.github/payments-composite-actions/deploy-infra-update
        with:
          deployment_config_path: ${{ inputs.deployment_config_path }}
          deployment_environment: ${{ inputs.deployment_environment }}
          github_token: ${{ secrets.GH_ACTIONS_CI_PAT }}
          chart_version: ${{ needs.chart_build.outputs.chart_version }}

      - name: "📝 Development deployment info"
        id: development_deploy_info
        run: |
          echo "#### [${{ inputs.deployment_environment }}] To Deploy please merge [Pull Request](https://github.com/sumup/deploy-infra/pull/${{ steps.deploy_infra_update.outputs.pr_number }})" >> $GITHUB_STEP_SUMMARY

      - name: "✉️ Send Slack message on failure"
        if: ${{ failure() }}
        uses: ./.github/payments-composite-actions/notifications/slack-send
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_channel: ${{ inputs.slack_channel }}
          color: "danger"
          message: "Failed to update the deploy infra repository!"

  ####
  ####   Send Slack notification
  ####
  notification:
    runs-on: ["self-hosted", "payments-tribe"]
    needs: [ 'deploy_repo' ]
    if: always() && needs.deploy_repo.result == 'success'
    steps:
      - name: "☁️ Check out payments composite actions"
        # actions checkout v 3.0.2
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          repository: 'sumup/payments-composite-actions@0.1.0'
          token: ${{ secrets.GH_ACTIONS_CI_PAT }}
          path: .github/payments-composite-actions
          ref: 'main'

      - name: "✉️ Send Slack message on success"
        if: ${{ success() }}
        uses: ./.github/payments-composite-actions/notifications/slack-send
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          color: "good"
          message: "Build completed successfully. Deploy infra pull request: https://github.com/sumup/deploy-infra/pull/${{ needs.deploy_repo.outputs.pr_number }}"
